
// @ts-nocheck
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.16.7
// Generated at: 2026-03-24T02:47:42.798Z
////////////////////////////////////////////////////////

import type { Client, Workflow } from '@botpress/client'

// Utility type to simplify complex types
type Simplify<T> = T extends (...args: infer A) => infer R
  ? (...args: SimplifyTuple<A>) => Simplify<R>
  : T extends Array<infer E>
    ? Array<Simplify<E>>
    : T extends ReadonlyArray<infer E>
      ? ReadonlyArray<Simplify<E>>
      : T extends Promise<infer R>
        ? Promise<Simplify<R>>
        : T extends Buffer
          ? Buffer
          : T extends object
            ? SimplifyObject<T>
            : T

type SimplifyTuple<T> = T extends [...infer A] ? { [K in keyof A]: Simplify<A[K]> } : never
type SimplifyObject<T extends object> = T extends infer O ? { [K in keyof O]: Simplify<O[K]> } : never

type GenericWorkflowInput = Record<string, any>
type GenericWorkflowOutput = Record<string, any>

type TypedWorkflow<TInput = GenericWorkflowInput, TOutput = GenericWorkflowOutput> = Simplify<
  Omit<Workflow, 'input' | 'output'> & {
    input: TInput
    output: TOutput
  }
>

// Extract response types from Client methods
type CreateWorkflowResponse = Simplify<Awaited<ReturnType<Client['createWorkflow']>>>
type GetWorkflowResponse = Simplify<Awaited<ReturnType<Client['getWorkflow']>>>
type UpdateWorkflowResponse = Simplify<Awaited<ReturnType<Client['updateWorkflow']>>>
type DeleteWorkflowResponse = Simplify<Awaited<ReturnType<Client['deleteWorkflow']>>>
type GetOrCreateWorkflowResponse = Simplify<Awaited<ReturnType<Client['getOrCreateWorkflow']>>>

type CreateTableRowsResponse = Simplify<Awaited<ReturnType<Client['createTableRows']>>>
type UpdateTableRowsResponse = Simplify<Awaited<ReturnType<Client['updateTableRows']>>>
type UpsertTableRowsResponse = Simplify<Awaited<ReturnType<Client['upsertTableRows']>>>
type DeleteTableRowsResponse = Simplify<Awaited<ReturnType<Client['deleteTableRows']>>>
type FindTableRowsResponse = Simplify<Awaited<ReturnType<Client['findTableRows']>>>
type GetTableRowResponse = Simplify<Awaited<ReturnType<Client['getTableRow']>>>

// Extract parameter types from Client methods
type ParamCreateWorkflow = Simplify<Parameters<Client['createWorkflow']>[0]>
type ParamGetWorkflow = Simplify<Parameters<Client['getWorkflow']>[0]>
type ParamUpdateWorkflow = Simplify<Parameters<Client['updateWorkflow']>[0]>
type ParamDeleteWorkflow = Simplify<Parameters<Client['deleteWorkflow']>[0]>
type ParamGetOrCreateWorkflow = Simplify<Parameters<Client['getOrCreateWorkflow']>[0]>

type ParamCreateTableRows = Simplify<Parameters<Client['createTableRows']>[0]>
type ParamUpdateTableRows = Simplify<Parameters<Client['updateTableRows']>[0]>
type ParamUpsertTableRows = Simplify<Parameters<Client['upsertTableRows']>[0]>
type ParamDeleteTableRows = Simplify<Parameters<Client['deleteTableRows']>[0]>
type ParamFindTableRows = Simplify<Parameters<Client['findTableRows']>[0]>
type ParamGetTableRow = Simplify<Parameters<Client['getTableRow']>[0]>

/**
 * Typed ADK Client
 *
 * Provides strongly-typed wrappers around the Botpress Client for actions, workflows, and tables.
 */
export interface AdkClient {
  /**
   * Typed action calls
   */
  actions: {
    
    /**
     * Call action: tablesRecomputeRows
     */
    'tablesRecomputeRows': (input: any) => Promise<any>
    
  }

  /**
   * Typed workflow operations
   */
  workflows: {
    
  }

  /**
   * Typed table operations
   */
  tables: {
    
    'ProjectTable': {
      /**
       * Find rows in table: ProjectTable
       */
      findTableRows: (params?: Omit<ParamFindTableRows, 'table'>) => Promise<Omit<FindTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      /**
       * Get a single row by ID
       */
      getTableRow: (params: Omit<ParamGetTableRow, 'table'>) => Promise<Omit<GetTableRowResponse, 'row'> & { row: { id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string } }>
      /**
       * Create rows in table: ProjectTable
       */
      createTableRows: (params: Omit<ParamCreateTableRows, 'table'>) => Promise<Omit<CreateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      /**
       * Update rows in table: ProjectTable
       */
      updateTableRows: (params: Omit<ParamUpdateTableRows, 'table'>) => Promise<Omit<UpdateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      /**
       * Upsert rows in table: ProjectTable
       */
      upsertTableRows: (params: Omit<ParamUpsertTableRows, 'table'>) => Promise<Omit<UpsertTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      /**
       * Delete rows by IDs
       */
      deleteTableRows: (params: Omit<ParamDeleteTableRows, 'table'>) => Promise<Omit<DeleteTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
    }
    

    'TaskTable': {
      /**
       * Find rows in table: TaskTable
       */
      findTableRows: (params?: Omit<ParamFindTableRows, 'table'>) => Promise<Omit<FindTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      /**
       * Get a single row by ID
       */
      getTableRow: (params: Omit<ParamGetTableRow, 'table'>) => Promise<Omit<GetTableRowResponse, 'row'> & { row: { id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string } }>
      /**
       * Create rows in table: TaskTable
       */
      createTableRows: (params: Omit<ParamCreateTableRows, 'table'>) => Promise<Omit<CreateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      /**
       * Update rows in table: TaskTable
       */
      updateTableRows: (params: Omit<ParamUpdateTableRows, 'table'>) => Promise<Omit<UpdateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      /**
       * Upsert rows in table: TaskTable
       */
      upsertTableRows: (params: Omit<ParamUpsertTableRows, 'table'>) => Promise<Omit<UpsertTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      /**
       * Delete rows by IDs
       */
      deleteTableRows: (params: Omit<ParamDeleteTableRows, 'table'>) => Promise<Omit<DeleteTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
    }
    

    'ArtifactTable': {
      /**
       * Find rows in table: ArtifactTable
       */
      findTableRows: (params?: Omit<ParamFindTableRows, 'table'>) => Promise<Omit<FindTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      /**
       * Get a single row by ID
       */
      getTableRow: (params: Omit<ParamGetTableRow, 'table'>) => Promise<Omit<GetTableRowResponse, 'row'> & { row: { id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string } }>
      /**
       * Create rows in table: ArtifactTable
       */
      createTableRows: (params: Omit<ParamCreateTableRows, 'table'>) => Promise<Omit<CreateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      /**
       * Update rows in table: ArtifactTable
       */
      updateTableRows: (params: Omit<ParamUpdateTableRows, 'table'>) => Promise<Omit<UpdateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      /**
       * Upsert rows in table: ArtifactTable
       */
      upsertTableRows: (params: Omit<ParamUpsertTableRows, 'table'>) => Promise<Omit<UpsertTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      /**
       * Delete rows by IDs
       */
      deleteTableRows: (params: Omit<ParamDeleteTableRows, 'table'>) => Promise<Omit<DeleteTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
    }
    
  }

  /**
   * Raw Botpress client (no additional typing)
   */
  client: Client
}

/**
 * Create a typed ADK client wrapper around a Botpress Client
 *
 * @example
 * ```typescript
 * import { Client } from '@botpress/client'
 * import { createAdkClient } from './.adk/client'
 *
 * const client = new Client({ token: 'xxx', botId: 'yyy' })
 * const adk = createAdkClient(client)
 *
 * // Typed action calls
 * const result = await adk.actions.myAction({ foo: 'bar' })
 *
 * // Typed workflow operations
 * const wf = await adk.workflows.myWorkflow.createWorkflow({ input: { data: 'value' } })
 * const workflow = await adk.workflows.myWorkflow.getWorkflow({ id: wf.workflow.id })
 * await adk.workflows.myWorkflow.updateWorkflow({ id: wf.workflow.id, status: 'completed' })
 * await adk.workflows.myWorkflow.deleteWorkflow({ id: wf.workflow.id })
 * await adk.workflows.myWorkflow.getOrCreateWorkflow({ key: 'unique-key', input: { data: 'value' } })
 *
 * // Typed table operations
 * const rows = await adk.tables.myTable.findTableRows({ filter: { name: 'John' } })
 * const row = await adk.tables.myTable.getTableRow({ id: 123 })
 * await adk.tables.myTable.createTableRows({ rows: [{ name: 'Jane', age: 30 }] })
 * await adk.tables.myTable.updateTableRows({ rows: [{ id: 123, name: 'Jane' }] })
 * await adk.tables.myTable.upsertTableRows({ rows: [{ name: 'Bob', age: 25 }] })
 * await adk.tables.myTable.deleteTableRows({ ids: [123, 456] })
 * ```
 */
export function createAdkClient(client: Client): AdkClient {
  return {
    actions: {
      
      'tablesRecomputeRows': async (input: any) => {
        const response = await client.callAction({
          type: 'tablesRecomputeRows',
          input,
        })
        return response.output as any
      }
      
    },

    workflows: {
      
    },

    tables: {
      
      'ProjectTable': {
        findTableRows: async (params) => {
          return client.findTableRows({
            table: 'ProjectTable',
            ...params,
          }) as any
        },
        getTableRow: async (params) => {
          return client.getTableRow({
            table: 'ProjectTable',
            ...params,
          }) as any
        },
        createTableRows: async (params) => {
          return client.createTableRows({
            table: 'ProjectTable',
            ...params,
          }) as any
        },
        updateTableRows: async (params) => {
          return client.updateTableRows({
            table: 'ProjectTable',
            ...params,
          }) as any
        },
        upsertTableRows: async (params) => {
          return client.upsertTableRows({
            table: 'ProjectTable',
            ...params,
          }) as any
        },
        deleteTableRows: async (params) => {
          return client.deleteTableRows({
            table: 'ProjectTable',
            ...params,
          }) as any
        },
      }
      ,

      'TaskTable': {
        findTableRows: async (params) => {
          return client.findTableRows({
            table: 'TaskTable',
            ...params,
          }) as any
        },
        getTableRow: async (params) => {
          return client.getTableRow({
            table: 'TaskTable',
            ...params,
          }) as any
        },
        createTableRows: async (params) => {
          return client.createTableRows({
            table: 'TaskTable',
            ...params,
          }) as any
        },
        updateTableRows: async (params) => {
          return client.updateTableRows({
            table: 'TaskTable',
            ...params,
          }) as any
        },
        upsertTableRows: async (params) => {
          return client.upsertTableRows({
            table: 'TaskTable',
            ...params,
          }) as any
        },
        deleteTableRows: async (params) => {
          return client.deleteTableRows({
            table: 'TaskTable',
            ...params,
          }) as any
        },
      }
      ,

      'ArtifactTable': {
        findTableRows: async (params) => {
          return client.findTableRows({
            table: 'ArtifactTable',
            ...params,
          }) as any
        },
        getTableRow: async (params) => {
          return client.getTableRow({
            table: 'ArtifactTable',
            ...params,
          }) as any
        },
        createTableRows: async (params) => {
          return client.createTableRows({
            table: 'ArtifactTable',
            ...params,
          }) as any
        },
        updateTableRows: async (params) => {
          return client.updateTableRows({
            table: 'ArtifactTable',
            ...params,
          }) as any
        },
        upsertTableRows: async (params) => {
          return client.upsertTableRows({
            table: 'ArtifactTable',
            ...params,
          }) as any
        },
        deleteTableRows: async (params) => {
          return client.deleteTableRows({
            table: 'ArtifactTable',
            ...params,
          }) as any
        },
      }
      
    },

    client,
  }
}
