
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.16.7
// Generated at: 2026-03-24T09:27:23.890Z
////////////////////////////////////////////////////////

type Integrations = import("@botpress/runtime/_types/integrations").Integrations;
type ConversationTags = import("@botpress/runtime/_types/tags").ConversationTags;
type MessageTags = import("@botpress/runtime/_types/tags").MessageTags;

declare module "@botpress/runtime/_types/conversations" {
  export type ConversationDefinitions = {
    "webchat.channel": {
      channel: "webchat.channel";
      integration: "webchat";
      state: {  };
      tags: Integrations["webchat"]["channels"]["channel"]["conversation"]["tags"] & ConversationTags;
      messageTags: Integrations["webchat"]["channels"]["channel"]["message"]["tags"] & MessageTags;
      messages: Integrations["webchat"]["channels"]["channel"]["messages"];
      events: Integrations["webchat"]["events"];
    };
  };

  /**
   * Events that can be routed to conversations (events with conversationId property).
   * Keyed by channel, containing a tuple of event names that have conversationId.
   */
  export type ConversationRoutableEvents = {
    "webchat.channel": readonly ["webchat:conversationStarted", "webchat:trigger"];
  };
}
