
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // ADK Version: 1.16.7
      // Generated at: 2026-03-24T09:27:23.869Z
      ////////////////////////////////////////////////////////

      declare module "@botpress/runtime/_types/integrations" {
        export type Integrations = {
          "webchat": import("./integrations/webchat/index.ts").Integration_All_Webchat, "chat": import("./integrations/chat/index.ts").Integration_All_Chat
        };
      }
      