
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // ADK Version: 1.16.7
      // Generated at: 2026-03-24T09:27:23.871Z
      ////////////////////////////////////////////////////////

      declare module "@botpress/runtime/_types/plugins" {
        export type Plugins = {
          
        };
      }
      