
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.16.7
// Generated at: 2026-03-24T09:27:23.901Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/channels" {
  export type Channels = "webchat.channel";
  export type ChannelSpec = Channels | readonly Channels[] | '*';
}

declare module "@botpress/runtime/_types/state" {
  export type BotState = { activeProjectId?: string; currentPhase?: 'ideation' | 'requirements' | 'architecture' | 'implementation' | 'testing' | 'deployment' | 'maintenance'; pipelineRunning: boolean };
  export type UserState = { role?: string; preferences?: { defaultLanguage: string; verbosity: 'minimal' | 'normal' | 'verbose' } };
}
