
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.16.7
// Generated at: 2026-03-24T09:27:23.884Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/tables" {
  export type TableDefinitions = {
    // Table: ProjectTable
    ProjectTable: {
      Input: {
        projectName: string;
        description: string;
        status: string;
        currentPhase: string;
        projectCreatedAt: string;
        projectUpdatedAt: string;
        metadata: string;
      };
      Output: {
        id: number;
        createdAt: string;
        updatedAt: string;
        projectName: string;
        description: string;
        status: string;
        currentPhase: string;
        projectCreatedAt: string;
        projectUpdatedAt: string;
        metadata: string;
      };
    };
    // Table: TaskTable
    TaskTable: {
      Input: {
        projectId: string;
        taskName: string;
        assignedBot: string;
        status: string;
        priority: string;
        inputArtifact: string;
        outputArtifact: string;
        taskCreatedAt: string;
        completedAt: string;
      };
      Output: {
        id: number;
        createdAt: string;
        updatedAt: string;
        projectId: string;
        taskName: string;
        assignedBot: string;
        status: string;
        priority: string;
        inputArtifact: string;
        outputArtifact: string;
        taskCreatedAt: string;
        completedAt: string;
      };
    };
    // Table: ArtifactTable
    ArtifactTable: {
      Input: {
        projectId: string;
        taskId: string;
        artifactType: string;
        title: string;
        content: string;
        version: string;
        artifactCreatedAt: string;
      };
      Output: {
        id: number;
        createdAt: string;
        updatedAt: string;
        projectId: string;
        taskId: string;
        artifactType: string;
        title: string;
        content: string;
        version: string;
        artifactCreatedAt: string;
      };
    };
  };
}
