
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.16.7
// Generated at: 2026-03-24T09:27:23.886Z
////////////////////////////////////////////////////////

declare module "@botpress/runtime/_types/tags" {
  /**
   * Bot-level tags defined in agent.config.ts
   */
  export type BotTags = Record<string, string | undefined>;

  /**
   * User-level tags defined in agent.config.ts
   */
  export type UserTags = Record<string, string | undefined>;

  /**
   * Conversation-level tags defined in agent.config.ts
   */
  export type ConversationTags = {
  /**
   * ADK Sync Timestamp
   * 
   * Built-in: Last synced message timestamp. Automatically updated by the ADK when messages are processed.
   */
  adkSyncTs?: string | undefined
  /** Project ID */
  projectId?: string | undefined
  /** Current Phase */
  phase?: string | undefined
};

  /**
   * Message-level tags defined in agent.config.ts
   */
  export type MessageTags = Record<string, string | undefined>;

  /**
   * Workflow-level tags defined in agent.config.ts
   */
  export type WorkflowTags = Record<string, string | undefined>;
}
