
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: chat
  // Version: 0.7.6
  // File: chat/actions.ts
  // Hash: 90752ad1ae4ccb37a5b7eff74726d7fe86cc9710f16707c5c3bf38129c0c6abe
  // Updated at: 2026-02-27T19:01:51.019Z
  ////////////////////////////////////////////////////////

  export type Integration_Actions_Chat = {
    /**
 * Title: Send Custom Event
 * Description: Send a custom event from the bot to the chat client
 */
    "sendEvent": {
      input: { 
/** The ID of the conversation to send the event to */
conversationId: string
; 
/** Custom data payload to send with the event */
payload:  { [key: string]: any }
 };
      output: {  };
    },
};