
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: chat
  // Version: 0.7.6
  // File: chat/channels.ts
  // Hash: 90752ad1ae4ccb37a5b7eff74726d7fe86cc9710f16707c5c3bf38129c0c6abe
  // Updated at: 2026-02-27T19:01:51.019Z
  ////////////////////////////////////////////////////////

  export type Integration_Channels_Chat = {
    /**
 * Title: channel
 * Description: No description
 */
    "channel": {
      conversation: {
        tags: {/**
 * Title: Foreign ID
 * Description: Copy of the foreign ID of the conversation
 */
["chat:fid"]?: string,
/**
 * Title: Conversation Owner
 * Description: ID of the user who created the conversation
 */
["chat:owner"]?: string,
};
      };
      message: {
        tags: {/**
 * Title: Foreign ID
 * Description: This tag is of no use and only exists for historical reasons
 */
["chat:fid"]?: string,
};
      };
      messages: {
"audio": { audioUrl: string; title?: string; metadata?:  { [key: string]: any } };

"bloc": { items: Array<
{ type: 'text'; payload: { text: string } } | { type: 'image'; payload: { imageUrl: string; title?: string } } | { type: 'audio'; payload: { audioUrl: string; title?: string } } | { type: 'video'; payload: { videoUrl: string; title?: string } } | { type: 'file'; payload: { fileUrl: string; title?: string } } | { type: 'location'; payload: { latitude: number; longitude: number; address?: string; title?: string } } | { type: 'markdown'; payload: { markdown: string } }>; metadata?:  { [key: string]: any } };

"card": { title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }>; metadata?:  { [key: string]: any } };

"carousel": { items: Array<{ title: string; subtitle?: string; imageUrl?: string; actions: Array<{ action: 'postback' | 'url' | 'say'; label: string; value: string }> }>; metadata?:  { [key: string]: any } };

"choice": { text: string; options: Array<{ label: string; value: string }>; metadata?:  { [key: string]: any } };

"dropdown": { text: string; options: Array<{ label: string; value: string }>; metadata?:  { [key: string]: any } };

"file": { fileUrl: string; title?: string; metadata?:  { [key: string]: any } };

"image": { imageUrl: string; title?: string; metadata?:  { [key: string]: any } };

"location": { latitude: number; longitude: number; address?: string; title?: string; metadata?:  { [key: string]: any } };

"markdown": { markdown: string; metadata?:  { [key: string]: any } };

"text": { text: string; metadata?:  { [key: string]: any } };

"video": { videoUrl: string; title?: string; metadata?:  { [key: string]: any } };

      };
    },
  };
  