
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: chat
  // Version: 0.7.6
  // File: chat/configurations.ts
  // Hash: 90752ad1ae4ccb37a5b7eff74726d7fe86cc9710f16707c5c3bf38129c0c6abe
  // Updated at: 2026-02-27T19:01:51.019Z
  ////////////////////////////////////////////////////////

  export type Integration_Configurations_Chat = {
  /**
     * @title Default
     * Default configuration
     */
  default: { 
/** Only set this config if you plan on signing your user key yourself. Key used to sign and verify user keys; JWT tokens with HS256 algorithm. */
encryptionKey?: string
; 
/** Only set this config if you want to listen on a webhook instead of the standard SSE stream. URL where all incoming and outgoing messages / events are sent to. */
webhookUrl?: string
; 
/** Secret forwarded to the webhook URL. */
webhookSecret?: string
 };
};