
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: chat
  // Version: 0.7.6
  // File: chat/events.ts
  // Hash: 90752ad1ae4ccb37a5b7eff74726d7fe86cc9710f16707c5c3bf38129c0c6abe
  // Updated at: 2026-02-27T19:01:51.019Z
  ////////////////////////////////////////////////////////

  export type Integration_Events_Chat = {
    /**
 * Title: Custom Event
 * Description: Custom event sent from the chat client to the bot
 */
    "custom": { 
/** The ID of the user who sent the custom event */
userId: string
; 
/** The ID of the conversation where the event was sent */
conversationId: string
; 
/** Custom data payload sent with the event */
payload:  { [key: string]: any }
 };
    
  };
  