
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: chat
  // Version: 0.7.6
  // File: chat/index.ts
  // Hash: 90752ad1ae4ccb37a5b7eff74726d7fe86cc9710f16707c5c3bf38129c0c6abe
  // Updated at: 2026-02-27T19:01:51.019Z
  ////////////////////////////////////////////////////////

  import { Integration_Actions_Chat } from "./actions";
  import { Integration_Channels_Chat } from "./channels";
  import { Integration_Events_Chat } from "./events";
  import { Integration_Users_Chat } from "./users";
  import { Integration_Configurations_Chat } from "./configurations";

  export * from "./actions";
  export * from "./channels";
  export * from "./events";
  export * from "./users";
  export * from "./configurations";

  export type Integration_All_Chat = {
    actions: Integration_Actions_Chat;
    channels: Integration_Channels_Chat;
    events: Integration_Events_Chat;
    users: Integration_Users_Chat;
    configurations: Integration_Configurations_Chat;
  };
  