
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: chat
  // Version: 0.7.6
  // File: chat/users.ts
  // Hash: 90752ad1ae4ccb37a5b7eff74726d7fe86cc9710f16707c5c3bf38129c0c6abe
  // Updated at: 2026-02-27T19:01:51.019Z
  ////////////////////////////////////////////////////////

  export type Integration_Users_Chat = {
    tags: /**
 * Title: Foreign ID
 * Description: Copy of the foreign ID of the user
 */
"chat:fid"
 | /**
 * Title: User Profile
 * Description: Custom profile data of the user encoded as a string
 */
"chat:profile"
;
  };
  