"""
migration_assistant.py — LLM-ready migration prompts for the AURA CLI
Typer + AutoGen migration assistant with 7-step structured prompts.
"""

from __future__ import annotations


class MigrationPrompts:
    """
    Provides 7 LLM-ready migration prompts covering the full Typer + AutoGen
    migration path for aura-cli. Each prompt is self-contained and references
    existing aura-cli integration points so an LLM can execute the step
    autonomously.
    """

    @staticmethod
    def step1_typer_cli_migration() -> str:
        return (
            "STEP 1 — Typer CLI Migration\n"
            "============================\n\n"
            "Goal: Replace the legacy argparse-based CLI in aura_cli/cli_options.py "
            "with a Typer application while preserving full backward compatibility "
            "with all existing commands and flags documented in docs/CLI_REFERENCE.md.\n\n"
            "Context: aura-cli currently dispatches commands through COMMAND_DISPATCH_REGISTRY "
            "in aura_cli/cli_main.py. Every command spec is defined in aura_cli/options.py. "
            "All CLI snapshot contracts live in tests/snapshots/ and are enforced by "
            "tests/test_cli_help_snapshots.py and tests/test_cli_error_snapshots.py.\n\n"
            "Instructions for the LLM:\n"
            "1. Read aura_cli/cli_options.py and aura_cli/options.py in full.\n"
            "2. Create a new aura_cli/typer_app.py that instantiates a typer.Typer() "
            "   app and registers sub-commands matching every entry in options.py.\n"
            "3. Map each argparse 'action' to a @app.command() decorated function. "
            "   Preserve all flag names, default values, and help strings exactly.\n"
            "4. Wire the Typer app into cli_main.py so that it is the primary entry "
            "   point when the AURA_USE_TYPER=1 environment variable is set, falling "
            "   back to the legacy argparse path otherwise.\n"
            "5. Run 'python3 scripts/generate_cli_reference.py' after wiring and update "
            "   any changed snapshots in tests/snapshots/.\n"
            "6. Ensure 'python3 -m pytest tests/test_cli_help_snapshots.py -q' passes.\n\n"
            "COMPLETE CODE TEMPLATE — aura_cli/typer_app.py skeleton:\n\n"
            "    import typer\n"
            "    from typing import Optional\n"
            "    from aura_cli.cli_main import COMMAND_DISPATCH_REGISTRY\n\n"
            "    app = typer.Typer(name='aura', help='AURA autonomous dev platform')\n\n"
            "    @app.command('goal-add')\n"
            "    def goal_add(goal: str = typer.Argument(..., help='Goal text'),\n"
            "                 run: bool = typer.Option(False, '--run', help='Execute immediately')):\n"
            "        '''Add a goal to the queue.'''\n"
            "        COMMAND_DISPATCH_REGISTRY['goal-add']({'goal': goal, 'run': run})\n\n"
            "    # Repeat for every command in options.COMMAND_SPECS.\n"
            "    # Use typer.Option for flags that have defaults.\n"
            "    # Use typer.Argument for positional parameters.\n\n"
            "Acceptance criteria:\n"
            "- All 5 snapshot test files pass unchanged.\n"
            "- AURA_USE_TYPER=0 (default) runs the legacy path.\n"
            "- AURA_USE_TYPER=1 runs the Typer path.\n"
            "- No API keys or credentials appear anywhere in this file.\n"
            "  Reference secrets via environment variables: ${ANTHROPIC_API_KEY}.\n"
        )

    @staticmethod
    def step2_two_agent_autogen_integration() -> str:
        return (
            "STEP 2 — Two-Agent AutoGen Integration\n"
            "=======================================\n\n"
            "Goal: Introduce a minimal two-agent AutoGen pattern (AssistantAgent + "
            "UserProxyAgent) into the AURA orchestration loop so that a conversational "
            "agent pair can handle task handoff before the main 10-phase loop runs.\n\n"
            "Context: The primary orchestration loop lives in core/orchestrator.py. "
            "Agent construction currently uses agents/registry.py default_agents(). "
            "The model adapter at core/model_adapter.py abstracts LLM calls and must "
            "continue to be the single point of LLM interaction to preserve secret masking "
            "in core/logging_utils.py.\n\n"
            "Instructions for the LLM:\n"
            "1. Install pyautogen (already in requirements.txt as 'pyautogen>=0.2').\n"
            "2. Create core/autogen_bridge.py with a build_two_agent_pair() factory that "
            "   returns (AssistantAgent, UserProxyAgent) configured to use the model "
            "   specified in settings.json under 'autogen_model'.\n"
            "3. In the AssistantAgent config, set llm_config to read the API key from "
            "   the environment variable at runtime — never embed a literal key.\n"
            "   Example: config_list = autogen.config_list_from_dotenv(env_or_file='.env')\n"
            "4. Add a new orchestrator phase 0 called 'negotiate' that invokes the agent "
            "   pair to clarify ambiguous goals before the Ingest phase.\n"
            "5. Gate the new phase with config flag 'autogen_negotiate: true' in "
            "   aura.config.json so existing behaviour is unchanged by default.\n\n"
            "COMPLETE CODE TEMPLATE — core/autogen_bridge.py:\n\n"
            "    from __future__ import annotations\n"
            "    import os\n"
            "    import autogen\n"
            "    from core.model_adapter import ModelAdapter\n\n"
            "    def build_two_agent_pair(\n"
            "        model: str = 'gpt-4o-mini',\n"
            "        temperature: float = 0.2,\n"
            "    ) -> tuple[autogen.AssistantAgent, autogen.UserProxyAgent]:\n"
            "        config_list = [{'model': model, 'api_key': os.environ['OPENAI_API_KEY']}]\n"
            "        assistant = autogen.AssistantAgent(\n"
            "            name='aura_assistant',\n"
            "            llm_config={'config_list': config_list, 'temperature': temperature},\n"
            "            system_message='You are AURA, an autonomous software development agent.',\n"
            "        )\n"
            "        proxy = autogen.UserProxyAgent(\n"
            "            name='aura_proxy',\n"
            "            human_input_mode='NEVER',\n"
            "            max_consecutive_auto_reply=3,\n"
            "            code_execution_config=False,\n"
            "        )\n"
            "        return assistant, proxy\n\n"
            "Acceptance criteria:\n"
            "- core/autogen_bridge.py imports cleanly with 'python3 -c \"from core.autogen_bridge import build_two_agent_pair\"'.\n"
            "- With 'autogen_negotiate: false' the existing test suite passes without modification.\n"
            "- API keys are read from ${OPENAI_API_KEY} or ${ANTHROPIC_API_KEY} at runtime.\n"
        )

    @staticmethod
    def step3_groupchat_ideation() -> str:
        return (
            "STEP 3 — GroupChat for Ideation\n"
            "================================\n\n"
            "Goal: Add an AutoGen GroupChat with round-robin speaker selection as an "
            "optional 'ideation' phase that runs before planning to generate diverse "
            "solution proposals for complex goals.\n\n"
            "Context: The planner phase in agents/planner.py currently generates a single "
            "plan. The critic in agents/critic.py adversarially reviews it. This step "
            "introduces a multi-agent brainstorm before the planner runs, surfacing more "
            "creative solutions. The GroupChat result is serialised and stored in the "
            "memory system (memory/brain.py) for later retrieval.\n\n"
            "Instructions for the LLM:\n"
            "1. Create agents/autogen_groupchat.py with a run_ideation_groupchat() function.\n"
            "2. Define three agents in the chat: Architect, Critic, and Implementer — each "
            "   with distinct system messages reflecting their role in AURA.\n"
            "3. Use autogen.GroupChat with speaker_selection_method='round_robin' and "
            "   max_round=6 so the chat terminates deterministically.\n"
            "4. Integrate into core/orchestrator.py as an optional phase between Ingest "
            "   and Skill Dispatch, gated by config flag 'groupchat_ideation: false'.\n"
            "5. Serialise the GroupChat transcript to a JSON string and write it to the "
            "   semantic memory store via memory/brain.py Brain.store_memory().\n"
            "6. Add a test in tests/test_groupchat_ideation.py that mocks autogen.GroupChat "
            "   and verifies the transcript is passed to Brain.store_memory().\n\n"
            "COMPLETE CODE TEMPLATE — agents/autogen_groupchat.py:\n\n"
            "    from __future__ import annotations\n"
            "    import json\n"
            "    import autogen\n"
            "    from memory.brain import Brain\n\n"
            "    AGENT_DEFS = [\n"
            "        ('Architect', 'You propose high-level software architecture solutions.'),\n"
            "        ('Critic', 'You identify risks and edge cases in proposed solutions.'),\n"
            "        ('Implementer', 'You translate proposals into concrete implementation steps.'),\n"
            "    ]\n\n"
            "    def run_ideation_groupchat(\n"
            "        goal: str,\n"
            "        config_list: list[dict],\n"
            "        brain: Brain | None = None,\n"
            "    ) -> list[dict]:\n"
            "        agents = [\n"
            "            autogen.AssistantAgent(name=name, llm_config={'config_list': config_list},\n"
            "                                   system_message=msg)\n"
            "            for name, msg in AGENT_DEFS\n"
            "        ]\n"
            "        groupchat = autogen.GroupChat(\n"
            "            agents=agents, messages=[], max_round=6,\n"
            "            speaker_selection_method='round_robin',\n"
            "        )\n"
            "        manager = autogen.GroupChatManager(groupchat=groupchat,\n"
            "                                           llm_config={'config_list': config_list})\n"
            "        agents[0].initiate_chat(manager, message=f'Brainstorm solutions for: {goal}')\n"
            "        transcript = groupchat.messages\n"
            "        if brain is not None:\n"
            "            brain.store_memory('ideation', json.dumps(transcript))\n"
            "        return transcript\n\n"
            "Acceptance criteria:\n"
            "- With 'groupchat_ideation: false' (default) all existing tests pass.\n"
            "- The new test file passes when autogen is installed.\n"
            "- No literal API key strings appear in any source file.\n"
        )

    @staticmethod
    def step4_swarm_handoff_self_evolution() -> str:
        return (
            "STEP 4 — Swarm Handoff Self-Evolution\n"
            "======================================\n\n"
            "Goal: Implement the AutoGen Swarm pattern so that agents can hand off tasks "
            "to one another autonomously, and integrate GitPython to automatically create "
            "pull requests when the swarm produces code changes.\n\n"
            "Context: AURA already has git utilities in core/git_tools.py. The evolution "
            "loop in core/evolution_loop.py handles self-improvement cycles. This step "
            "wires the swarm into the evolution loop so that code improvements discovered "
            "by one agent are passed to a specialist agent for refinement and then "
            "committed via core/git_tools.py with an auto-generated PR description.\n\n"
            "Instructions for the LLM:\n"
            "1. Read core/git_tools.py to understand the existing commit/push interface.\n"
            "2. Create core/swarm_evolution.py with a SwarmEvolver class.\n"
            "3. SwarmEvolver.__init__ accepts a list of AgentSpec dataclasses (name, role, "
            "   llm_config) and constructs one autogen.AssistantAgent per spec.\n"
            "4. Implement SwarmEvolver.run(goal, context) which initiates a chat from the "
            "   first agent; each agent ends its reply with 'HANDOFF: <AgentName>' to "
            "   trigger the next agent, following the AutoGen Swarm convention.\n"
            "5. After the swarm completes, extract file changes from the final agent's "
            "   output, apply them via core/file_tools.py, and call core/git_tools.py "
            "   create_branch_and_commit() with the swarm summary as the commit message.\n"
            "6. Optionally open a GitHub PR via aura_cli/mcp_github_bridge.py if the "
            "   environment variable AURA_AUTO_PR=true is set.\n\n"
            "COMPLETE CODE TEMPLATE — core/swarm_evolution.py:\n\n"
            "    from __future__ import annotations\n"
            "    import os\n"
            "    from dataclasses import dataclass\n"
            "    import autogen\n"
            "    from core import git_tools, file_tools\n\n"
            "    @dataclass\n"
            "    class AgentSpec:\n"
            "        name: str\n"
            "        role: str\n"
            "        llm_config: dict\n\n"
            "    class SwarmEvolver:\n"
            "        def __init__(self, specs: list[AgentSpec]) -> None:\n"
            "            self.agents = [\n"
            "                autogen.AssistantAgent(name=s.name, llm_config=s.llm_config,\n"
            "                                       system_message=s.role)\n"
            "                for s in specs\n"
            "            ]\n\n"
            "        def run(self, goal: str, context: str = '') -> str:\n"
            "            proxy = autogen.UserProxyAgent(\n"
            "                name='swarm_proxy', human_input_mode='NEVER',\n"
            "                max_consecutive_auto_reply=len(self.agents) * 2,\n"
            "                code_execution_config=False,\n"
            "            )\n"
            "            self.agents[0].initiate_chat(proxy, message=goal)\n"
            "            return proxy.last_message()['content']\n\n"
            "Acceptance criteria:\n"
            "- SwarmEvolver imports cleanly without autogen installed (guard with try/except ImportError).\n"
            "- AURA_AUTO_PR=false (default) disables PR creation.\n"
            "- All git operations go through core/git_tools.py — no direct subprocess calls.\n"
            "- No literal secret values appear in any committed file; use ${GITHUB_TOKEN}.\n"
        )

    @staticmethod
    def step5_hierarchical_nested_patterns() -> str:
        return (
            "STEP 5 — Hierarchical and Nested Agent Patterns\n"
            "================================================\n\n"
            "Goal: Extend AURA's multi-agent system with hierarchical and nested team "
            "patterns, where a top-level orchestrator agent delegates to specialised "
            "sub-teams (planning team, coding team, verification team) that each run "
            "their own inner AutoGen GroupChat.\n\n"
            "Context: The main orchestrator in core/orchestrator.py currently runs a "
            "flat 10-phase loop. This step introduces a meta-orchestrator layer that "
            "partitions the loop into three nested teams, each responsible for a subset "
            "of phases, enabling parallel execution and more fine-grained specialisation.\n\n"
            "Instructions for the LLM:\n"
            "1. Create core/hierarchical_orchestrator.py with a HierarchicalOrchestrator "
            "   class that wraps the existing Orchestrator from core/orchestrator.py.\n"
            "2. Define three TeamSpec dataclasses: PlanningTeam (phases 1-3), CodingTeam "
            "   (phases 4-6), and VerificationTeam (phases 7-10).\n"
            "3. Each team runs an inner autogen.GroupChat with agents specialised for its "
            "   phases. The GroupChat transcript is passed as context to the next team.\n"
            "4. The HierarchicalOrchestrator.run(goal) method sequences the three teams "
            "   and aggregates their outputs into a final LoopResult (use core/types.py).\n"
            "5. Add a config flag 'hierarchical_mode: false' in aura.config.json to gate "
            "   the new path. Existing behaviour is unchanged when the flag is false.\n"
            "6. Add integration tests in tests/integration/test_hierarchical_orchestrator.py "
            "   that mock all three team GroupChats and verify phase sequencing.\n\n"
            "COMPLETE CODE TEMPLATE — core/hierarchical_orchestrator.py:\n\n"
            "    from __future__ import annotations\n"
            "    from dataclasses import dataclass, field\n"
            "    from typing import Any\n"
            "    try:\n"
            "        import autogen\n"
            "        AUTOGEN_AVAILABLE = True\n"
            "    except ImportError:\n"
            "        AUTOGEN_AVAILABLE = False\n"
            "    from core.types import LoopResult\n\n"
            "    @dataclass\n"
            "    class TeamSpec:\n"
            "        name: str\n"
            "        phases: list[str]\n"
            "        agent_roles: list[str] = field(default_factory=list)\n\n"
            "    TEAM_SPECS = [\n"
            "        TeamSpec('planning', ['ingest', 'skill_dispatch', 'plan'], ['Planner', 'Critic']),\n"
            "        TeamSpec('coding',   ['synthesize', 'act', 'sandbox'],     ['Coder', 'Debugger']),\n"
            "        TeamSpec('verify',   ['apply', 'verify', 'reflect'],        ['Verifier', 'Reflector']),\n"
            "    ]\n\n"
            "    class HierarchicalOrchestrator:\n"
            "        def __init__(self, config: dict[str, Any]) -> None:\n"
            "            self.config = config\n\n"
            "        def run(self, goal: str) -> LoopResult:\n"
            "            context = goal\n"
            "            for team in TEAM_SPECS:\n"
            "                context = self._run_team(team, context)\n"
            "            return LoopResult(success=True, summary=context)\n\n"
            "        def _run_team(self, team: TeamSpec, context: str) -> str:\n"
            "            # Each team runs its own inner GroupChat.\n"
            "            # Return the final message as context for the next team.\n"
            "            return f'[{team.name} completed] {context[:200]}'\n\n"
            "Acceptance criteria:\n"
            "- HierarchicalOrchestrator imports without autogen if the library is absent.\n"
            "- 'hierarchical_mode: false' leaves the existing 10-phase loop fully intact.\n"
            "- Integration tests pass with mocked GroupChats.\n"
            "- core/types.py LoopResult is used unchanged — no new fields added.\n"
        )

    @staticmethod
    def step6_captain_agent_auto_build() -> str:
        return (
            "STEP 6 — CaptainAgent Auto-Build\n"
            "=================================\n\n"
            "Goal: Use the AutoGen CaptainAgent pattern to automatically generate a team "
            "of expert agents whose roles and capabilities are derived from a static "
            "analysis of the aura-cli codebase graph (memory/brain.py NetworkX graph).\n\n"
            "Context: memory/brain.py maintains a NetworkX semantic graph of the codebase. "
            "agents/registry.py provides the default_agents() factory. This step adds a "
            "CaptainAgent that reads the graph to identify capability gaps and spawns new "
            "AutoGen agents on-the-fly to fill them, then registers them in the registry.\n\n"
            "Instructions for the LLM:\n"
            "1. Read memory/brain.py to understand the graph schema (node types, edge types).\n"
            "2. Read agents/registry.py to understand the AgentWrapper protocol.\n"
            "3. Create agents/captain_agent.py with a CaptainAgent class.\n"
            "4. CaptainAgent.analyse_graph(brain) queries the graph for nodes with "
            "   attribute 'capability_gap=True' and returns a list of CapabilitySpec.\n"
            "5. CaptainAgent.build_team(specs, llm_config) instantiates one "
            "   autogen.AssistantAgent per CapabilitySpec and wraps each in an "
            "   AgentWrapper compatible with agents/registry.py.\n"
            "6. CaptainAgent.register(registry) adds the new agents to the registry so "
            "   the main loop can dispatch tasks to them in subsequent cycles.\n"
            "7. Gate activation with config flag 'captain_agent: false' in aura.config.json.\n\n"
            "COMPLETE CODE TEMPLATE — agents/captain_agent.py:\n\n"
            "    from __future__ import annotations\n"
            "    import os\n"
            "    from dataclasses import dataclass\n"
            "    from typing import Any\n"
            "    try:\n"
            "        import autogen\n"
            "        AUTOGEN_AVAILABLE = True\n"
            "    except ImportError:\n"
            "        AUTOGEN_AVAILABLE = False\n"
            "    from memory.brain import Brain\n"
            "    from agents.registry import AgentRegistry\n\n"
            "    @dataclass\n"
            "    class CapabilitySpec:\n"
            "        name: str\n"
            "        description: str\n"
            "        priority: int = 1\n\n"
            "    class CaptainAgent:\n"
            "        def analyse_graph(self, brain: Brain) -> list[CapabilitySpec]:\n"
            "            specs = []\n"
            "            for node, data in brain.graph.nodes(data=True):\n"
            "                if data.get('capability_gap'):\n"
            "                    specs.append(CapabilitySpec(\n"
            "                        name=str(node),\n"
            "                        description=data.get('description', ''),\n"
            "                        priority=data.get('priority', 1),\n"
            "                    ))\n"
            "            return sorted(specs, key=lambda s: s.priority, reverse=True)\n\n"
            "        def build_team(\n"
            "            self, specs: list[CapabilitySpec], llm_config: dict[str, Any]\n"
            "        ) -> list[Any]:\n"
            "            if not AUTOGEN_AVAILABLE:\n"
            "                return []\n"
            "            return [\n"
            "                autogen.AssistantAgent(\n"
            "                    name=s.name,\n"
            "                    llm_config=llm_config,\n"
            "                    system_message=s.description,\n"
            "                )\n"
            "                for s in specs\n"
            "            ]\n\n"
            "        def register(self, agents: list[Any], registry: AgentRegistry) -> None:\n"
            "            for agent in agents:\n"
            "                registry.register(agent.name, agent)\n\n"
            "Acceptance criteria:\n"
            "- CaptainAgent.analyse_graph returns an empty list when the brain graph has "
            "  no capability_gap nodes (existing behaviour unchanged).\n"
            "- build_team returns [] when autogen is not installed.\n"
            "- No literal API key values appear in any committed file; read keys from "
            "  the environment: os.environ.get('OPENAI_API_KEY') or ${ANTHROPIC_API_KEY}.\n"
            "- 'captain_agent: false' (default) leaves registry.py default_agents() intact.\n"
        )

    @staticmethod
    def step7_full_migration_roadmap() -> str:
        return (
            "STEP 7 — Full Migration Roadmap (ADR + PR Checklist)\n"
            "======================================================\n\n"
            "Goal: Synthesise the outputs of Steps 1-6 into a formal Architecture "
            "Decision Record (ADR) and a pull-request checklist that can be executed "
            "by an LLM or a human engineer to land the complete Typer + AutoGen "
            "migration into the main branch of aura-cli.\n\n"
            "Context: Each of the preceding six steps introduced an independent, "
            "flag-gated capability. This final step ties them together by producing "
            "two deliverables: (1) an ADR markdown file at docs/ADR-001-autogen-migration.md "
            "and (2) a GitHub PR description template at docs/PR_TEMPLATE_MIGRATION.md. "
            "Both documents reference the existing CI workflow at .github/workflows/ci.yml "
            "and the snapshot contract system in tests/snapshots/.\n\n"
            "Instructions for the LLM:\n"
            "1. Generate docs/ADR-001-autogen-migration.md with sections: Status, Context, "
            "   Decision, Consequences, and Alternatives Considered. Reference each of the "
            "   six implementation steps by file name (e.g., aura_cli/typer_app.py, "
            "   core/autogen_bridge.py, agents/autogen_groupchat.py, core/swarm_evolution.py, "
            "   core/hierarchical_orchestrator.py, agents/captain_agent.py).\n"
            "2. Generate docs/PR_TEMPLATE_MIGRATION.md with a markdown checklist covering:\n"
            "   a. All six feature flags defaulting to false in aura.config.json.\n"
            "   b. New test files present and passing (python3 -m pytest -q).\n"
            "   c. CLI snapshot contracts passing (tests/snapshots/).\n"
            "   d. docs/CLI_REFERENCE.md regenerated via scripts/generate_cli_reference.py.\n"
            "   e. No literal secret values committed (secret scanner returns clean).\n"
            "   f. AGENTS.md and CLAUDE.md updated with new architecture sections.\n"
            "3. Create a migration validation script at scripts/validate_migration.py that "
            "   imports each new module, checks each feature flag defaults to false, and "
            "   runs a smoke test of the Typer app with AURA_USE_TYPER=1.\n\n"
            "COMPLETE CODE TEMPLATE — scripts/validate_migration.py:\n\n"
            "    #!/usr/bin/env python3\n"
            "    '''Smoke-test all six migration steps. Exit 0 on success, 1 on failure.'''\n"
            "    import os, sys\n"
            "    import importlib\n\n"
            "    REQUIRED_MODULES = [\n"
            "        'aura_cli.typer_app',\n"
            "        'core.autogen_bridge',\n"
            "        'agents.autogen_groupchat',\n"
            "        'core.swarm_evolution',\n"
            "        'core.hierarchical_orchestrator',\n"
            "        'agents.captain_agent',\n"
            "        'aura_cli.migration_assistant',\n"
            "    ]\n\n"
            "    FEATURE_FLAGS = [\n"
            "        'autogen_negotiate', 'groupchat_ideation', 'swarm_evolution',\n"
            "        'hierarchical_mode', 'captain_agent',\n"
            "    ]\n\n"
            "    def main() -> int:\n"
            "        errors: list[str] = []\n"
            "        for module_name in REQUIRED_MODULES:\n"
            "            try:\n"
            "                importlib.import_module(module_name)\n"
            "                print(f'  OK  {module_name}')\n"
            "            except ImportError as exc:\n"
            "                errors.append(f'FAIL {module_name}: {exc}')\n"
            "        import json\n"
            "        with open('aura.config.json') as f:\n"
            "            config = json.load(f)\n"
            "        for flag in FEATURE_FLAGS:\n"
            "            if config.get(flag, False):\n"
            "                errors.append(f'FAIL feature flag {flag!r} must default to false')\n"
            "            else:\n"
            "                print(f'  OK  feature flag {flag} = false')\n"
            "        if errors:\n"
            "            print('\\nMigration validation FAILED:')\n"
            "            for e in errors:\n"
            "                print(f'  {e}')\n"
            "            return 1\n"
            "        print('\\nAll migration checks passed.')\n"
            "        return 0\n\n"
            "    if __name__ == '__main__':\n"
            "        sys.exit(main())\n\n"
            "Acceptance criteria:\n"
            "- docs/ADR-001-autogen-migration.md exists and references all six module paths.\n"
            "- docs/PR_TEMPLATE_MIGRATION.md checklist has at least 10 items.\n"
            "- scripts/validate_migration.py exits 0 when all six modules are present and "
            "  all feature flags are false.\n"
            "- CI passes: python3 -m pytest -q && python3 scripts/generate_cli_reference.py --check.\n"
            "- No secrets (${ANTHROPIC_API_KEY}, ${OPENAI_API_KEY}, ${GITHUB_TOKEN}) are "
            "  embedded as literal values in any committed file.\n"
        )

    @classmethod
    def get_all_migration_prompts(cls) -> list[dict]:
        """Return all 7 migration prompts as a list of dicts with step, title, and prompt keys."""
        return [
            {
                "step": 1,
                "title": "Typer CLI Migration",
                "prompt": cls.step1_typer_cli_migration(),
            },
            {
                "step": 2,
                "title": "Two-Agent AutoGen Integration",
                "prompt": cls.step2_two_agent_autogen_integration(),
            },
            {
                "step": 3,
                "title": "GroupChat for Ideation",
                "prompt": cls.step3_groupchat_ideation(),
            },
            {
                "step": 4,
                "title": "Swarm Handoff Self-Evolution",
                "prompt": cls.step4_swarm_handoff_self_evolution(),
            },
            {
                "step": 5,
                "title": "Hierarchical and Nested Patterns",
                "prompt": cls.step5_hierarchical_nested_patterns(),
            },
            {
                "step": 6,
                "title": "CaptainAgent Auto-Build",
                "prompt": cls.step6_captain_agent_auto_build(),
            },
            {
                "step": 7,
                "title": "Full Migration Roadmap",
                "prompt": cls.step7_full_migration_roadmap(),
            },
        ]
