
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/actions.ts
  // Hash: ecb52bf32a4af60c631e0e3d9404af1ab488cb4cccfa5df4793f203297e2c430
  // Updated at: 2026-03-13T19:06:24.453Z
  ////////////////////////////////////////////////////////

  export type Integration_Actions_Webchat = {
    /**
 * Title: Configure Webchat
 * Description: Update the webchat configuration during a conversation
 */
    "configWebchat": {
      input: { 
/** The conversation id of the webchat instance. Usually {{event.conversationId}} */
conversationId: string
; 
/** A JSON string representing the new configuration. You can use {{JSON.stringify(workflow.someVariable)}} to convert an object to JSON */
config: string
 };
      output: {  };
    },

    /**
 * Title: Send Custom Event
 * Description: Initiate this action to dispatch a custom event to the webchat. Please ensure to appropriately handle this event within your webpage's code. Usage:
 * 
 * window.botpressWebChat.onEvent(event => {}, ['TRIGGER'])
 */
    "customEvent": {
      input: { 
/** The conversation id of the webchat instance. Usually {{event.conversationId}} */
conversationId: string
; 
/** An event as JSON to send to the webchat instance */
event: string
 };
      output: {  };
    },

    /**
 * Title: Get or Create a User
 * Description: Proactively create a user from a bot
 */
    "getOrCreateUser": {
      input: { name?: string; pictureUrl?: string; email?: string; user: { 
/** Some unique identifier for the user */
id: string
; 
/** The ID of the conversation in which to add the user */
conversationId: string
 } };
      output: { userId: string };
    },

    /**
 * Title: Get User Data
 * Description: Get the user's information that was provided when the webchat is initialized.
 */
    "getUserData": {
      input: { 
/** The ID of the user. Usually you can access it using {{event.userId}} */
userId: string
 };
      output: { userData?:  { [key: string]: string } };
    },

    /**
 * Title: Hide Webchat
 * Description: Hide the webchat widget
 */
    "hideWebchat": {
      input: { 
/** The conversation id of the webchat instance. Usually {{event.conversationId}} */
conversationId: string
 };
      output: {  };
    },

    /**
 * Title: Show Webchat
 * Description: Show the webchat widget
 */
    "showWebchat": {
      input: { 
/** The conversation id of the webchat instance. Usually {{event.conversationId}} */
conversationId: string
 };
      output: {  };
    },

    /**
 * Title: startTypingIndicator
 * Description: No description
 */
    "startTypingIndicator": {
      input: { conversationId: string; messageId: string; timeout?: number };
      output: {  };
    },

    /**
 * Title: stopTypingIndicator
 * Description: No description
 */
    "stopTypingIndicator": {
      input: { conversationId: string; messageId: string };
      output: {  };
    },

    /**
 * Title: Toggle Webchat
 * Description: Toggle the visibility of the webchat widget
 */
    "toggleWebchat": {
      input: { 
/** The conversation id of the webchat instance. Usually {{event.conversationId}} */
conversationId: string
 };
      output: {  };
    },
};