
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/configurations.ts
  // Hash: ecb52bf32a4af60c631e0e3d9404af1ab488cb4cccfa5df4793f203297e2c430
  // Updated at: 2026-03-13T19:06:24.453Z
  ////////////////////////////////////////////////////////

  export type Integration_Configurations_Webchat = {
  /**
     * @title Default
     * Default configuration
     */
  default: { 
/** The JWT public key used to verify tokens. When specified, userData and attributes in createUser and updateUser should be signed JWT tokens. */
jwtPublicKey?: string
; 
/** The secret key required to manage users */
adminSecret?: string
; version?: string; botDisplayName?: string; botAvatarUrl?: string; botDescription?: string; fabImage?: string; descriptionPhoneNumber?: { title?: string; link?: string }; descriptionEmailAddress?: { title?: string; link?: string }; descriptionWebsiteUrl?: { title?: string; link?: string }; termsConditionsUrl?: { title?: string; link?: string }; privacyPolicyUrl?: { title?: string; link?: string }; botComposerPlaceholder?: string; showPoweredByBotpress?: boolean; additionalStylesheet?: string; additionalStylesheetUrl?: string; allowedOrigins?: string[]; primaryColor?: string; borderRadiusScale?: number; themeMode?: 'light' | 'dark'; variant?: 'solid' | 'soft'; headerVariant?: 'solid' | 'glass'; fontFamily?: string; feedbackEnabled?: boolean; showPoweredBy?: boolean; footer?: string; allowFileUpload?: boolean; storageLocation?: 'sessionStorage' | 'localStorage'; soundEnabled?: boolean; toggleChatId?: string; embeddedChatId?: string; proactiveMessageEnabled?: boolean; proactiveBubbleMessage?: string; proactiveBubbleTriggerType?: 'afterDelay' | 'userIdle'; proactiveBubbleDelayTime?: number; conversationHistory?: boolean; _debug?: boolean };
};