
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/events.ts
  // Hash: ecb52bf32a4af60c631e0e3d9404af1ab488cb4cccfa5df4793f203297e2c430
  // Updated at: 2026-03-13T19:06:24.453Z
  ////////////////////////////////////////////////////////

  export type Integration_Events_Webchat = {
    /**
 * Title: Conversation Started
 * Description: This event occurs when a user activates the webchat widget, prompting the interface to appear.
 */
    "conversationStarted": { userId: string; conversationId: string };
    
    /**
 * Title: Custom Trigger (advanced)
 * Description: This event occurs when a payload is sent from the browser. That payload will be available in {{event.payload}}. Usage:
 * 
 * window.botpressWebChat.sendPayload({ type: 'trigger', payload: {} })
 */
    "trigger": { 
/** The origin of the event trigger */
origin: 'website'
; 
/** The webchat userId that triggered the event */
userId: string
; 
/** The webchat conversationId that triggered the event */
conversationId: string
; 
/** The payload to send with the event */
payload:  { [key: string]: any }
 };
    
  };
  