
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/index.ts
  // Hash: ecb52bf32a4af60c631e0e3d9404af1ab488cb4cccfa5df4793f203297e2c430
  // Updated at: 2026-03-13T19:06:24.453Z
  ////////////////////////////////////////////////////////

  import { Integration_Actions_Webchat } from "./actions";
  import { Integration_Channels_Webchat } from "./channels";
  import { Integration_Events_Webchat } from "./events";
  import { Integration_Users_Webchat } from "./users";
  import { Integration_Configurations_Webchat } from "./configurations";

  export * from "./actions";
  export * from "./channels";
  export * from "./events";
  export * from "./users";
  export * from "./configurations";

  export type Integration_All_Webchat = {
    actions: Integration_Actions_Webchat;
    channels: Integration_Channels_Webchat;
    events: Integration_Events_Webchat;
    users: Integration_Users_Webchat;
    configurations: Integration_Configurations_Webchat;
  };
  