
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Integration: webchat
  // Version: 0.3.0
  // File: webchat/users.ts
  // Hash: ecb52bf32a4af60c631e0e3d9404af1ab488cb4cccfa5df4793f203297e2c430
  // Updated at: 2026-03-13T19:06:24.453Z
  ////////////////////////////////////////////////////////

  export type Integration_Users_Webchat = {
    tags: /**
 * Title: undefined
 * Description: undefined
 */
"webchat:id"
;
  };
  