
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Interface: typing-indicator
  // Integrations: webchat
  // Version: 0.0.3
  // File: typing_indicator/index.ts
  // Hash: 344880f9d6fcbe51823b739bae0269990c8ea05b60a5281a519488f047717c6e
  // Updated at: 2025-12-16T19:34:19.049Z
  ////////////////////////////////////////////////////////

  export type Interface_Actions_TypingIndicator = {
    
    // Integration: webchat (webchat@0.3.0)
    // Updated at: 2026-03-13T19:06:24.453Z
    "webchat": {
      /**
 * Title: startTypingIndicator
 * Description: No description
 */
      "startTypingIndicator": {
        input: { conversationId: string; 
/** The message ID to which the typing indicator should be attached */
messageId: string
; 
/** The timeout in milliseconds after which the typing indicator should stop */
timeout?: number
 };
        output: {  };
      },

      /**
 * Title: stopTypingIndicator
 * Description: No description
 */
      "stopTypingIndicator": {
        input: { conversationId: string; 
/** The message ID from which the typing indicator should be removed */
messageId: string
 };
        output: {  };
      },
};
  };

  export const Interface_Actions_TypingIndicator = {
    "webchat:startTypingIndicator": "webchat:startTypingIndicator",
    "webchat:stopTypingIndicator": "webchat:stopTypingIndicator"
  };

  