
  ////////////////////////////////////////////////////////
  // DO NOT EDIT THIS FILE DIRECTLY
  // This file is auto-generated from the Botpress ADK
  // ADK Version: 1.16.7
  // Interface: typing-indicator
  // Integrations: webchat
  // Version: 0.0.3
  // File: typing_indicator/index.ts
  // Hash: 344880f9d6fcbe51823b739bae0269990c8ea05b60a5281a519488f047717c6e
  // Updated at: 2025-12-16T19:34:19.049Z
  ////////////////////////////////////////////////////////

  import { Interface_Actions_TypingIndicator } from "./actions";

  export * from "./actions";

  export type Interface_All_TypingIndicator = {
    actions: Interface_Actions_TypingIndicator;
  };

  export const Interface_All_TypingIndicator = {
    actions: Interface_Actions_TypingIndicator,
  }
  