#!/usr/bin/env python3
"""
Auto-Test Generator - Generates pytest test cases from coverage gaps.

This tool reads coverage_gaps.json (generated by coverage_gap_analyzer.py),
uses CoderAgent with LLM to generate pytest test cases for high-impact
uncovered functions, and outputs to tests/auto/ directory.

Usage:
    python tools/auto_test_generator.py [--coverage-gaps PATH] [--output-dir PATH]

Example:
    python tools/auto_test_generator.py --coverage-gaps coverage_gaps.json --output-dir tests/auto/
"""

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Set
from datetime import datetime

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent.parent))

from core.logging_utils import log_json


@dataclass
class TestCase:
    """Represents a generated test case."""
    gap_id: str
    target_function: str
    target_file: str
    test_name: str
    test_code: str
    fixtures: List[str] = field(default_factory=list)
    imports: List[str] = field(default_factory=list)
    description: str = ""


@dataclass
class GeneratedTestSuite:
    """Collection of generated tests for a module."""
    module_name: str
    target_file: str
    test_cases: List[TestCase] = field(default_factory=list)
    shared_fixtures: Dict[str, str] = field(default_factory=dict)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())


class AutoTestGenerator:
    """Generates pytest tests from coverage gaps using LLM."""
    
    def __init__(
        self,
        project_root: Optional[Path] = None,
        output_dir: Optional[Path] = None,
        min_severity: str = "medium",
        max_tests_per_module: int = 10
    ):
        """
        Initialize the auto-test generator.
        
        Args:
            project_root: Root directory of the project
            output_dir: Directory to output generated tests
            min_severity: Minimum severity level to generate tests for
            max_tests_per_module: Maximum tests to generate per module
        """
        self.project_root = project_root or Path.cwd()
        self.output_dir = output_dir or self.project_root / "tests" / "auto"
        self.min_severity = min_severity
        self.max_tests_per_module = max_tests_per_module
        
        self.coverage_gaps: List[Dict[str, Any]] = []
        self.generated_suites: List[GeneratedTestSuite] = []
        
        # Ensure output directory exists
        self.output_dir.mkdir(parents=True, exist_ok=True)
    
    def load_coverage_gaps(self, coverage_gaps_path: Path) -> bool:
        """
        Load coverage gaps from JSON file.
        
        Args:
            coverage_gaps_path: Path to coverage_gaps.json
            
        Returns:
            True if loaded successfully
        """
        try:
            with open(coverage_gaps_path) as f:
                data = json.load(f)
            
            self.coverage_gaps = data.get("gaps", [])
            
            # Filter by severity
            severity_levels = {"critical": 4, "high": 3, "medium": 2, "low": 1}
            min_level = severity_levels.get(self.min_severity, 1)
            
            self.coverage_gaps = [
                g for g in self.coverage_gaps
                if severity_levels.get(g.get("severity", "low"), 0) >= min_level
            ]
            
            log_json("INFO", "coverage_gaps_loaded", {
                "total": len(data.get("gaps", [])),
                "filtered": len(self.coverage_gaps),
                "min_severity": self.min_severity
            })
            
            return True
            
        except Exception as e:
            log_json("ERROR", "coverage_gaps_load_failed", {"error": str(e)})
            return False
    
    def _generate_test_name(self, function_name: str, gap_id: str) -> str:
        """Generate a descriptive test name from function name."""
        # Convert function name to test name
        test_name = f"test_{function_name}"
        
        # Add gap ID suffix for uniqueness
        gap_suffix = gap_id.replace("gap_", "")
        test_name = f"{test_name}_gap{gap_suffix}"
        
        return test_name
    
    def _analyze_function_signature(self, file_path: Path, function_name: str) -> Dict[str, Any]:
        """
        Analyze function signature from source code.
        
        Args:
            file_path: Path to source file
            function_name: Name of function to analyze
            
        Returns:
            Dictionary with function metadata
        """
        try:
            if not file_path.exists():
                return {"error": "File not found"}
            
            with open(file_path) as f:
                content = f.read()
            
            # Find function definition
            pattern = rf'^(async\s+)?def\s+{re.escape(function_name)}\s*\((.*?)\)(?:\s*->\s*([^:]+))?:'
            match = re.search(pattern, content, re.MULTILINE | re.DOTALL)
            
            if not match:
                return {"error": "Function not found"}
            
            is_async = match.group(1) is not None
            params = match.group(2)
            return_type = match.group(3).strip() if match.group(3) else None
            
            # Parse parameters
            param_list = []
            if params.strip():
                # Simple parameter parsing (doesn't handle complex type hints)
                for param in params.split(','):
                    param = param.strip()
                    if param == 'self' or param == 'cls':
                        continue
                    if '=' in param:
                        param_name = param.split('=')[0].strip().split(':')[0].strip()
                        has_default = True
                    else:
                        param_name = param.split(':')[0].strip()
                        has_default = False
                    if param_name:
                        param_list.append({
                            "name": param_name,
                            "has_default": has_default
                        })
            
            return {
                "is_async": is_async,
                "parameters": param_list,
                "return_type": return_type,
                "signature": f"{function_name}({params})"
            }
            
        except Exception as e:
            return {"error": str(e)}
    
    def _read_function_source(self, file_path: Path, function_name: str, line_number: int) -> str:
        """Read function source code from file."""
        try:
            if not file_path.exists():
                return ""
            
            with open(file_path) as f:
                lines = f.readlines()
            
            # Find function start (line_number is 1-indexed)
            start_idx = line_number - 1
            if start_idx >= len(lines):
                return ""
            
            # Calculate initial indentation
            first_line = lines[start_idx]
            base_indent = len(first_line) - len(first_line.lstrip())
            
            # Collect function lines until we hit same or lower indentation
            func_lines = []
            for i in range(start_idx, len(lines)):
                line = lines[i]
                if line.strip():
                    line_indent = len(line) - len(line.lstrip())
                    if line_indent <= base_indent and i > start_idx:
                        break
                func_lines.append(line)
            
            return ''.join(func_lines)
            
        except Exception as e:
            log_json("WARN", "function_read_failed", {"error": str(e)})
            return ""
    
    def _extract_docstring(self, source_code: str) -> str:
        """Extract docstring from function source."""
        # Match triple-quoted docstrings
        match = re.search(r'"""(.*?)"""', source_code, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        match = re.search(r"'''(.*?)'''", source_code, re.DOTALL)
        if match:
            return match.group(1).strip()
        
        return ""
    
    def _infer_test_cases_from_function(
        self,
        gap: Dict[str, Any],
        func_sig: Dict[str, Any],
        source_code: str
    ) -> List[Dict[str, Any]]:
        """
        Infer test cases from function analysis.
        
        This is a simplified rule-based approach that generates basic test cases
        without actual LLM calls. In a full implementation, this would use
        the CoderAgent with LLM to generate intelligent tests.
        """
        test_cases = []
        function_name = gap["function_name"]
        docstring = self._extract_docstring(source_code)
        
        # Check for common patterns in the code
        has_error_handling = "try:" in source_code or "raise" in source_code
        has_conditionals = "if " in source_code or "elif" in source_code
        has_loops = "for " in source_code or "while " in source_code
        
        # Generate happy path test
        happy_path = {
            "name": f"test_{function_name}_happy_path",
            "description": f"Test {function_name} with valid input",
            "assertions": ["result is not None", "result == expected"],
            "mock_dependencies": False
        }
        test_cases.append(happy_path)
        
        # Generate error handling test if function has error handling
        if has_error_handling:
            error_test = {
                "name": f"test_{function_name}_error_handling",
                "description": f"Test {function_name} error handling with invalid input",
                "assertions": ["raises(ValueError) or raises(TypeError)"],
                "mock_dependencies": False
            }
            test_cases.append(error_test)
        
        # Generate edge case tests if function has conditionals
        if has_conditionals:
            edge_test = {
                "name": f"test_{function_name}_edge_cases",
                "description": f"Test {function_name} with edge case inputs",
                "assertions": ["handles empty input", "handles None input"],
                "mock_dependencies": False
            }
            test_cases.append(edge_test)
        
        # Generate boundary test if function has loops
        if has_loops:
            boundary_test = {
                "name": f"test_{function_name}_boundary",
                "description": f"Test {function_name} with boundary conditions (empty list, single item)",
                "assertions": ["handles empty collection", "handles single item"],
                "mock_dependencies": False
            }
            test_cases.append(boundary_test)
        
        return test_cases
    
    def _generate_test_code(
        self,
        gap: Dict[str, Any],
        test_case: Dict[str, Any],
        func_sig: Dict[str, Any],
        source_code: str
    ) -> str:
        """Generate actual Python test code."""
        function_name = gap["function_name"]
        file_path = gap["file_path"]
        module_path = file_path.replace("/", ".").replace(".py", "")
        is_async = func_sig.get("is_async", False)
        
        # Generate imports
        imports = [
            "import pytest",
            f"from {module_path} import {function_name}"
        ]
        
        # Generate test code
        test_code_lines = [f"def {test_case['name']}():"]
        test_code_lines.append(f'    \"\"\"')
        test_code_lines.append(f'    {test_case["description"]}')
        test_code_lines.append(f'    Gap ID: {gap["id"]}')
        test_code_lines.append(f'    Severity: {gap["severity"]}')
        test_code_lines.append(f'    Impact Score: {gap["impact_score"]}')
        test_code_lines.append(f'    \"\"\"')
        test_code_lines.append("")
        
        # Arrange
        test_code_lines.append("    # Arrange")
        test_code_lines.append("    # TODO: Set up test inputs")
        
        for param in func_sig.get("parameters", []):
            test_code_lines.append(f"    {param['name']} = None  # Configure test input")
        
        test_code_lines.append("")
        
        # Act
        test_code_lines.append("    # Act")
        if is_async:
            test_code_lines.append(f"    # result = asyncio.run({function_name}(...))")
        else:
            test_code_lines.append(f"    # result = {function_name}(...)")
        test_code_lines.append("")
        
        # Assert
        test_code_lines.append("    # Assert")
        for assertion in test_case.get("assertions", []):
            test_code_lines.append(f"    # assert {assertion}")
        
        test_code_lines.append("    pass  # TODO: Replace with actual assertions")
        test_code_lines.append("")
        
        return "\n".join(test_code_lines)
    
    def generate_tests_for_gap(self, gap: Dict[str, Any]) -> Optional[TestCase]:
        """
        Generate test case(s) for a single coverage gap.
        
        Args:
            gap: Coverage gap dictionary
            
        Returns:
            Generated test case or None
        """
        try:
            file_path = self.project_root / gap["file_path"]
            function_name = gap["function_name"]
            line_number = gap["line_number"]
            
            # Analyze function
            func_sig = self._analyze_function_signature(file_path, function_name)
            
            if "error" in func_sig:
                log_json("WARN", "function_analysis_failed", {
                    "file": gap["file_path"],
                    "function": function_name,
                    "error": func_sig["error"]
                })
                return None
            
            # Read function source
            source_code = self._read_function_source(file_path, function_name, line_number)
            
            # Infer test cases
            test_cases = self._infer_test_cases_from_function(gap, func_sig, source_code)
            
            if not test_cases:
                return None
            
            # For now, generate the first test case
            # In a full implementation with LLM, we'd generate all test cases
            test_case = test_cases[0]
            
            test_code = self._generate_test_code(gap, test_case, func_sig, source_code)
            
            return TestCase(
                gap_id=gap["id"],
                target_function=function_name,
                target_file=gap["file_path"],
                test_name=test_case["name"],
                test_code=test_code,
                description=test_case["description"]
            )
            
        except Exception as e:
            log_json("ERROR", "test_generation_failed", {
                "gap_id": gap.get("id"),
                "error": str(e)
            })
            return None
    
    def group_gaps_by_module(self) -> Dict[str, List[Dict[str, Any]]]:
        """Group coverage gaps by target module."""
        modules: Dict[str, List[Dict[str, Any]]] = {}
        
        for gap in self.coverage_gaps:
            file_path = gap["file_path"]
            module_name = file_path.replace("/", "_").replace(".py", "")
            
            if module_name not in modules:
                modules[module_name] = []
            
            modules[module_name].append(gap)
        
        return modules
    
    def generate_all_tests(self) -> int:
        """
        Generate tests for all coverage gaps.
        
        Returns:
            Number of test cases generated
        """
        total_generated = 0
        
        # Group gaps by module
        modules = self.group_gaps_by_module()
        
        for module_name, gaps in modules.items():
            log_json("INFO", "generating_tests_for_module", {
                "module": module_name,
                "gaps": len(gaps)
            })
            
            # Limit tests per module
            gaps_to_process = gaps[:self.max_tests_per_module]
            
            test_cases = []
            for gap in gaps_to_process:
                test_case = self.generate_tests_for_gap(gap)
                if test_case:
                    test_cases.append(test_case)
                    total_generated += 1
            
            if test_cases:
                suite = GeneratedTestSuite(
                    module_name=module_name,
                    target_file=gaps[0]["file_path"],
                    test_cases=test_cases
                )
                self.generated_suites.append(suite)
        
        log_json("INFO", "test_generation_complete", {
            "total_generated": total_generated,
            "modules": len(self.generated_suites)
        })
        
        return total_generated
    
    def _generate_file_header(self, suite: GeneratedTestSuite) -> str:
        """Generate file header with imports and docstring."""
        header = f'''"""
Auto-generated tests for {suite.module_name}

Generated by auto_test_generator.py
Timestamp: {suite.timestamp}
Target file: {suite.target_file}

This file contains automatically generated tests based on coverage gaps.
Each test targets a specific uncovered function identified by the coverage analyzer.
"""

import pytest
import asyncio
from unittest.mock import Mock, patch, AsyncMock
from typing import Any, Dict, List, Optional

'''
        return header
    
    def _generate_shared_fixtures(self, suite: GeneratedTestSuite) -> str:
        """Generate shared pytest fixtures."""
        fixtures = []
        
        # Add common fixtures
        fixtures.append('''
@pytest.fixture
def mock_dependencies():
    """Fixture for mocking common dependencies."""
    return Mock()

@pytest.fixture
def event_loop():
    """Create an instance of the default event loop for async tests."""
    loop = asyncio.get_event_loop_policy().new_event_loop()
    yield loop
    loop.close()
''')
        
        return "\n".join(fixtures)
    
    def write_test_file(self, suite: GeneratedTestSuite) -> Optional[Path]:
        """
        Write generated tests to file.
        
        Args:
            suite: Generated test suite
            
        Returns:
            Path to written file or None
        """
        try:
            file_name = f"test_{suite.module_name}.py"
            file_path = self.output_dir / file_name
            
            # Build file content
            content_parts = []
            
            # Header
            content_parts.append(self._generate_file_header(suite))
            
            # Fixtures
            content_parts.append(self._generate_shared_fixtures(suite))
            content_parts.append("\n")
            
            # Test cases
            for test_case in suite.test_cases:
                content_parts.append(f"# Gap ID: {test_case.gap_id}")
                content_parts.append(f"# Target: {test_case.target_function} in {test_case.target_file}")
                content_parts.append(test_case.test_code)
                content_parts.append("\n")
            
            # Write file
            with open(file_path, 'w') as f:
                f.write('\n'.join(content_parts))
            
            log_json("INFO", "test_file_written", {
                "path": str(file_path),
                "tests": len(suite.test_cases)
            })
            
            return file_path
            
        except Exception as e:
            log_json("ERROR", "test_file_write_failed", {
                "module": suite.module_name,
                "error": str(e)
            })
            return None
    
    def write_all_tests(self) -> List[Path]:
        """
        Write all generated test files.
        
        Returns:
            List of paths to written files
        """
        written_files = []
        
        for suite in self.generated_suites:
            file_path = self.write_test_file(suite)
            if file_path:
                written_files.append(file_path)
        
        return written_files
    
    def generate_report(self) -> Dict[str, Any]:
        """Generate summary report of test generation."""
        total_tests = sum(len(s.test_cases) for s in self.generated_suites)
        
        return {
            "timestamp": datetime.utcnow().isoformat(),
            "output_directory": str(self.output_dir),
            "total_suites": len(self.generated_suites),
            "total_tests": total_tests,
            "coverage_gaps_processed": len(self.coverage_gaps),
            "suites": [
                {
                    "module": s.module_name,
                    "tests": len(s.test_cases),
                    "target": s.target_file
                }
                for s in self.generated_suites
            ]
        }


def main():
    """Main entry point for CLI usage."""
    parser = argparse.ArgumentParser(
        description="Generate pytest tests from coverage gaps"
    )
    parser.add_argument(
        "--coverage-gaps", "-c",
        type=str,
        default="coverage_gaps.json",
        help="Path to coverage_gaps.json file (default: coverage_gaps.json)"
    )
    parser.add_argument(
        "--output-dir", "-o",
        type=str,
        default="tests/auto",
        help="Output directory for generated tests (default: tests/auto)"
    )
    parser.add_argument(
        "--min-severity", "-s",
        type=str,
        choices=["critical", "high", "medium", "low"],
        default="medium",
        help="Minimum severity level to generate tests for (default: medium)"
    )
    parser.add_argument(
        "--max-per-module", "-m",
        type=int,
        default=10,
        help="Maximum tests per module (default: 10)"
    )
    parser.add_argument(
        "--project-root", "-p",
        type=str,
        default=".",
        help="Project root directory (default: current directory)"
    )
    parser.add_argument(
        "--dry-run", "-d",
        action="store_true",
        help="Show what would be generated without writing files"
    )
    
    args = parser.parse_args()
    
    # Initialize generator
    generator = AutoTestGenerator(
        project_root=Path(args.project_root),
        output_dir=Path(args.output_dir),
        min_severity=args.min_severity,
        max_tests_per_module=args.max_per_module
    )
    
    # Load coverage gaps
    coverage_gaps_path = Path(args.coverage_gaps)
    if not generator.load_coverage_gaps(coverage_gaps_path):
        print("❌ Failed to load coverage gaps", file=sys.stderr)
        sys.exit(1)
    
    # Generate tests
    total_generated = generator.generate_all_tests()
    
    if total_generated == 0:
        print("⚠️ No tests were generated")
        sys.exit(0)
    
    # Dry run or write files
    if args.dry_run:
        report = generator.generate_report()
        print("\n📋 DRY RUN - Would generate:")
        print(json.dumps(report, indent=2))
    else:
        written_files = generator.write_all_tests()
        report = generator.generate_report()
        
        print(f"\n✅ Generated {report['total_tests']} tests in {len(written_files)} files:")
        for file_path in written_files:
            print(f"   - {file_path}")
        
        print(f"\n📊 Summary:")
        print(f"   Total suites: {report['total_suites']}")
        print(f"   Total tests: {report['total_tests']}")
        print(f"   Coverage gaps processed: {report['coverage_gaps_processed']}")


if __name__ == "__main__":
    main()
