
      ////////////////////////////////////////////////////////
      // DO NOT EDIT THIS FILE DIRECTLY
      // This file is auto-generated from the Botpress ADK
      // File: tables.ts
      ////////////////////////////////////////////////////////

      import * as tables_1 from "../../../src/tables/project-table";
import * as tables_2 from "../../../src/tables/task-table";
import * as tables_3 from "../../../src/tables/artifact-table";

      export const Tables = {
        "ProjectTable": tables_1.default,
"TaskTable": tables_2.default,
"ArtifactTable": tables_3.default
      };
      