
// @ts-nocheck
////////////////////////////////////////////////////////
// DO NOT EDIT THIS FILE DIRECTLY
// This file is auto-generated from the Botpress ADK
// ADK Version: 1.16.7
// Generated at: 2026-03-24T02:47:42.798Z
////////////////////////////////////////////////////////

import type { Client, Workflow } from '@botpress/client'

type Simplify<T> = T extends (...args: infer A) => infer R
  ? (...args: SimplifyTuple<A>) => Simplify<R>
  : T extends Array<infer E>
    ? Array<Simplify<E>>
    : T extends ReadonlyArray<infer E>
      ? ReadonlyArray<Simplify<E>>
      : T extends Promise<infer R>
        ? Promise<Simplify<R>>
        : T extends Buffer
          ? Buffer
          : T extends object
            ? SimplifyObject<T>
            : T

type SimplifyTuple<T> = T extends [...infer A] ? { [K in keyof A]: Simplify<A[K]> } : never
type SimplifyObject<T extends object> = T extends infer O ? { [K in keyof O]: Simplify<O[K]> } : never

type GenericWorkflowInput = Record<string, any>
type GenericWorkflowOutput = Record<string, any>

type TypedWorkflow<TInput = GenericWorkflowInput, TOutput = GenericWorkflowOutput> = Simplify<
  Omit<Workflow, 'input' | 'output'> & {
    input: TInput
    output: TOutput
  }
>

type CreateWorkflowResponse = Simplify<Awaited<ReturnType<Client['createWorkflow']>>>
type GetWorkflowResponse = Simplify<Awaited<ReturnType<Client['getWorkflow']>>>
type UpdateWorkflowResponse = Simplify<Awaited<ReturnType<Client['updateWorkflow']>>>
type DeleteWorkflowResponse = Simplify<Awaited<ReturnType<Client['deleteWorkflow']>>>
type GetOrCreateWorkflowResponse = Simplify<Awaited<ReturnType<Client['getOrCreateWorkflow']>>>

type CreateTableRowsResponse = Simplify<Awaited<ReturnType<Client['createTableRows']>>>
type UpdateTableRowsResponse = Simplify<Awaited<ReturnType<Client['updateTableRows']>>>
type UpsertTableRowsResponse = Simplify<Awaited<ReturnType<Client['upsertTableRows']>>>
type DeleteTableRowsResponse = Simplify<Awaited<ReturnType<Client['deleteTableRows']>>>
type FindTableRowsResponse = Simplify<Awaited<ReturnType<Client['findTableRows']>>>
type GetTableRowResponse = Simplify<Awaited<ReturnType<Client['getTableRow']>>>

type ParamCreateWorkflow = Simplify<Parameters<Client['createWorkflow']>[0]>
type ParamGetWorkflow = Simplify<Parameters<Client['getWorkflow']>[0]>
type ParamUpdateWorkflow = Simplify<Parameters<Client['updateWorkflow']>[0]>
type ParamDeleteWorkflow = Simplify<Parameters<Client['deleteWorkflow']>[0]>
type ParamGetOrCreateWorkflow = Simplify<Parameters<Client['getOrCreateWorkflow']>[0]>

type ParamCreateTableRows = Simplify<Parameters<Client['createTableRows']>[0]>
type ParamUpdateTableRows = Simplify<Parameters<Client['updateTableRows']>[0]>
type ParamUpsertTableRows = Simplify<Parameters<Client['upsertTableRows']>[0]>
type ParamDeleteTableRows = Simplify<Parameters<Client['deleteTableRows']>[0]>
type ParamFindTableRows = Simplify<Parameters<Client['findTableRows']>[0]>
type ParamGetTableRow = Simplify<Parameters<Client['getTableRow']>[0]>

export interface AdkClient {
  actions: {
    'tablesRecomputeRows': (input: any) => Promise<any>
  }
  workflows: {}
  tables: {
    'ProjectTable': {
      findTableRows: (params?: Omit<ParamFindTableRows, 'table'>) => Promise<Omit<FindTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      getTableRow: (params: Omit<ParamGetTableRow, 'table'>) => Promise<Omit<GetTableRowResponse, 'row'> & { row: { id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string } }>
      createTableRows: (params: Omit<ParamCreateTableRows, 'table'>) => Promise<Omit<CreateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      updateTableRows: (params: Omit<ParamUpdateTableRows, 'table'>) => Promise<Omit<UpdateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      upsertTableRows: (params: Omit<ParamUpsertTableRows, 'table'>) => Promise<Omit<UpsertTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
      deleteTableRows: (params: Omit<ParamDeleteTableRows, 'table'>) => Promise<Omit<DeleteTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectName: string; description: string; status: string; currentPhase: string; projectCreatedAt: string; projectUpdatedAt: string; metadata: string }> }>
    }
    'TaskTable': {
      findTableRows: (params?: Omit<ParamFindTableRows, 'table'>) => Promise<Omit<FindTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      getTableRow: (params: Omit<ParamGetTableRow, 'table'>) => Promise<Omit<GetTableRowResponse, 'row'> & { row: { id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string } }>
      createTableRows: (params: Omit<ParamCreateTableRows, 'table'>) => Promise<Omit<CreateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      updateTableRows: (params: Omit<ParamUpdateTableRows, 'table'>) => Promise<Omit<UpdateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      upsertTableRows: (params: Omit<ParamUpsertTableRows, 'table'>) => Promise<Omit<UpsertTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
      deleteTableRows: (params: Omit<ParamDeleteTableRows, 'table'>) => Promise<Omit<DeleteTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskName: string; assignedBot: string; status: string; priority: string; inputArtifact: string; outputArtifact: string; taskCreatedAt: string; completedAt: string }> }>
    }
    'ArtifactTable': {
      findTableRows: (params?: Omit<ParamFindTableRows, 'table'>) => Promise<Omit<FindTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      getTableRow: (params: Omit<ParamGetTableRow, 'table'>) => Promise<Omit<GetTableRowResponse, 'row'> & { row: { id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string } }>
      createTableRows: (params: Omit<ParamCreateTableRows, 'table'>) => Promise<Omit<CreateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      updateTableRows: (params: Omit<ParamUpdateTableRows, 'table'>) => Promise<Omit<UpdateTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      upsertTableRows: (params: Omit<ParamUpsertTableRows, 'table'>) => Promise<Omit<UpsertTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
      deleteTableRows: (params: Omit<ParamDeleteTableRows, 'table'>) => Promise<Omit<DeleteTableRowsResponse, 'rows'> & { rows: Array<{ id: number; createdAt: string; updatedAt: string; projectId: string; taskId: string; artifactType: string; title: string; content: string; version: string; artifactCreatedAt: string }> }>
    }
  }
  client: Client
}

export function createAdkClient(client: Client): AdkClient {
  return {
    actions: {
      'tablesRecomputeRows': async (input: any) => {
        const response = await client.callAction({ type: 'tablesRecomputeRows', input })
        return response.output as any
      }
    },
    workflows: {},
    tables: {
      'ProjectTable': {
        findTableRows: async (params) => client.findTableRows({ table: 'ProjectTable', ...params }) as any,
        getTableRow: async (params) => client.getTableRow({ table: 'ProjectTable', ...params }) as any,
        createTableRows: async (params) => client.createTableRows({ table: 'ProjectTable', ...params }) as any,
        updateTableRows: async (params) => client.updateTableRows({ table: 'ProjectTable', ...params }) as any,
        upsertTableRows: async (params) => client.upsertTableRows({ table: 'ProjectTable', ...params }) as any,
        deleteTableRows: async (params) => client.deleteTableRows({ table: 'ProjectTable', ...params }) as any,
      },
      'TaskTable': {
        findTableRows: async (params) => client.findTableRows({ table: 'TaskTable', ...params }) as any,
        getTableRow: async (params) => client.getTableRow({ table: 'TaskTable', ...params }) as any,
        createTableRows: async (params) => client.createTableRows({ table: 'TaskTable', ...params }) as any,
        updateTableRows: async (params) => client.updateTableRows({ table: 'TaskTable', ...params }) as any,
        upsertTableRows: async (params) => client.upsertTableRows({ table: 'TaskTable', ...params }) as any,
        deleteTableRows: async (params) => client.deleteTableRows({ table: 'TaskTable', ...params }) as any,
      },
      'ArtifactTable': {
        findTableRows: async (params) => client.findTableRows({ table: 'ArtifactTable', ...params }) as any,
        getTableRow: async (params) => client.getTableRow({ table: 'ArtifactTable', ...params }) as any,
        createTableRows: async (params) => client.createTableRows({ table: 'ArtifactTable', ...params }) as any,
        updateTableRows: async (params) => client.updateTableRows({ table: 'ArtifactTable', ...params }) as any,
        upsertTableRows: async (params) => client.upsertTableRows({ table: 'ArtifactTable', ...params }) as any,
        deleteTableRows: async (params) => client.deleteTableRows({ table: 'ArtifactTable', ...params }) as any,
      },
    },
    client,
  }
}
